apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: edb-cluster
  namespace: edb-postgresql
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi