apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acs-operator
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: "latest"
  installPlanApproval: Automatic
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace